name: Update gist with WakaTime stats
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 0caf94a50300fd79c026defef93fcf9f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
